# Generated by Django 2.2.7 on 2019-11-22 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=20, verbose_name='案件名')),
                ('job_details', models.CharField(max_length=250, verbose_name='案件詳細')),
                ('offer_amount', models.IntegerField(verbose_name='オファー金額')),
                ('work_location', models.CharField(max_length=30, verbose_name='勤務地')),
                ('work_period', models.CharField(max_length=30, verbose_name='勤務期間')),
                ('reply_deadline', models.DateField(verbose_name='応募期限')),
                ('Employment_status', models.IntegerField(choices=[(1, '正社員'), (2, '契約社員'), (3, 'アルバイト')], verbose_name='雇用形態')),
                ('date_offered', models.DateTimeField(auto_now_add=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.JobSeeker', verbose_name='求職者')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Recruiter', verbose_name='リクルーター')),
            ],
        ),
    ]
