# Generated by Django 2.2.7 on 2019-11-24 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlist',
            name='Employment_status',
            field=models.CharField(choices=[('正社員', '正社員'), ('契約社員', '契約社員'), ('アルバイト', 'アルバイト')], max_length=5, verbose_name='雇用形態'),
        ),
        migrations.AlterField(
            model_name='offerlist',
            name='reply_deadline',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='応募期限'),
        ),
    ]
