# Generated by Django 2.2.7 on 2019-11-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlist',
            name='offer_amount',
            field=models.IntegerField(verbose_name='オファー金額'),
        ),
    ]
