# Generated by Django 2.2.7 on 2019-11-22 16:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='username')),
                ('last_name', models.CharField(max_length=20, verbose_name='姓')),
                ('first_name', models.CharField(max_length=20, verbose_name='名')),
                ('ruby_last_name', models.CharField(max_length=20, verbose_name='ふりがな(姓)')),
                ('ruby_first_name', models.CharField(max_length=20, verbose_name='ふりがな(名)')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='氏名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('purpose', models.IntegerField(blank=True, choices=[(1, '仕事をお探しの方'), (2, '求人をお考えの方')], verbose_name='目的')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', registration.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='所属企業名')),
                ('ruby_company_name', models.CharField(max_length=50, verbose_name='ふりがな(所属企業名)')),
                ('postal_code', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='正しい郵便番号を入力してください', regex='^[0-9]+$')], verbose_name='郵便番号')),
                ('address', models.CharField(max_length=120, verbose_name='住所')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='正しい電話番号を入力してください', regex='^[0-9]+$')], verbose_name='電話番号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(1, '男性'), (2, '女性')], verbose_name='性別')),
                ('date_of_birth', models.DateField(verbose_name='誕生日')),
                ('postal_code', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='正しい郵便番号を入力してください', regex='^[0-9]+$')], verbose_name='郵便番号')),
                ('address', models.CharField(max_length=120, verbose_name='住所')),
                ('nearest_station', models.CharField(max_length=20, verbose_name='最寄り駅')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='正しい電話番号を入力してください', regex='^[0-9]+$')], verbose_name='電話番号')),
                ('Academic_history', models.CharField(max_length=50, verbose_name='最終学歴')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='DesiredCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=30, verbose_name='活かしたいスキル')),
                ('job_change', models.IntegerField(choices=[(1, '転職'), (2, '副業')], verbose_name='転職 or 副業')),
                ('monthly_income', models.IntegerField(verbose_name='希望月収')),
                ('hourly_wage', models.IntegerField(verbose_name='希望時給')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.JobSeeker', verbose_name='求職者')),
            ],
        ),
    ]
